apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-exporter.fullname" . }}
  labels:
    {{- include "cert-exporter.certManagerLabels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: {{ .Values.service.portName }}
      targetPort: 8080
  selector:
    {{ include "cert-exporter.certManagerSelectorLabels" . | nindent 6 }}
