apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: cert-exporter-nodes
  name: cert-exporter-nodes
spec:
  selector:
    matchLabels:
      name: cert-exporter-nodes
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        name: cert-exporter-nodes
    spec:
      containers:
      - image: joeelliott/cert-exporter:v2.11.0
        name: cert-exporter-nodes
        command: ["./app"]
        args:
        - --include-kubeconfig-glob=/var/lib/*/kubeconfig
        - --include-cert-glob=/srv/kubernetes/*.crt
        - --logtostderr
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - mountPath: /var/lib/kubelet
          mountPropagation: HostToContainer
          name: kubelet
          readOnly: true
        - mountPath: /var/lib/kube-proxy
          name: kube-proxy
          readOnly: true
        - mountPath: /srv/kubernetes
          name: kube-root
          readOnly: true
        securityContext:
          runAsUser: 0
      volumes:
      - name: kubelet
        hostPath:
          path: /var/lib/kubelet
          type: Directory
      - name: kube-proxy
        hostPath:
          path: /var/lib/kube-proxy
          type: Directory
      - name: kube-root
        hostPath:
          path: /srv/kubernetes
          type: Directory
